=== jjdeharo/kit_ia_exelearning/plantillas/plantilla_avanzada_aula/content.dtd
<!ELEMENT ode (userPreferences?, odeResources?, odeProperties?, odeNavStructures)>
<!ATTLIST ode
    xmlns CDATA #IMPLIED
    version CDATA #IMPLIED>

<!ELEMENT userPreferences (userPreference*)>
<!ELEMENT userPreference (key, value)>

<!ELEMENT odeResources (odeResource*)>
<!ELEMENT odeResource (key, value)>

<!ELEMENT odeProperties (odeProperty*)>
<!ELEMENT odeProperty (key, value)>

<!ELEMENT odeNavStructures (odeNavStructure+)>
<!ELEMENT odeNavStructure (odePageId, odeParentPageId, pageName, odeNavStructureOrder, odeNavStructureProperties?, odePagStructures)>
<!ELEMENT odeNavStructureProperties (odeNavStructureProperty*)>
<!ELEMENT odeNavStructureProperty (key, value)>

<!ELEMENT odePagStructures (odePagStructure+)>
<!ELEMENT odePagStructure (odePageId, odeBlockId, blockName, iconName, odePagStructureOrder, odePagStructureProperties?, odeComponents)>
<!ELEMENT odePagStructureProperties (odePagStructureProperty*)>
<!ELEMENT odePagStructureProperty (key, value)>

<!ELEMENT odeComponents (odeComponent+)>
<!ELEMENT odeComponent (odePageId, odeBlockId, odeIdeviceId, odeIdeviceTypeName, htmlView, jsonProperties, odeComponentsOrder, odeComponentsProperties?)>
<!ELEMENT odeComponentsProperties (odeComponentsProperty*)>
<!ELEMENT odeComponentsProperty (key, value)>

<!ELEMENT odePageId (#PCDATA)>
<!ELEMENT odeParentPageId (#PCDATA)>
<!ELEMENT pageName (#PCDATA)>
<!ELEMENT odeNavStructureOrder (#PCDATA)>
<!ELEMENT odeBlockId (#PCDATA)>
<!ELEMENT blockName (#PCDATA)>
<!ELEMENT iconName (#PCDATA)>
<!ELEMENT odePagStructureOrder (#PCDATA)>
<!ELEMENT odeIdeviceId (#PCDATA)>
<!ELEMENT odeIdeviceTypeName (#PCDATA)>
<!ELEMENT htmlView (#PCDATA)>
<!ELEMENT jsonProperties (#PCDATA)>
<!ELEMENT odeComponentsOrder (#PCDATA)>
<!ELEMENT key (#PCDATA)>
<!ELEMENT value (#PCDATA)>

=== jjdeharo/kit_ia_exelearning/plantillas/tema_nova/content.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ode SYSTEM "content.dtd">
<ode xmlns="http://www.intef.es/xsd/ode" version="2.0">
<userPreferences>
  <userPreference>
    <key>theme</key>
    <value>nova</value>
  </userPreference>
</userPreferences>
<odeResources>
  <odeResource>
    <key>odeId</key>
    <value>2026030310490322P38D</value>
  </odeResource>
  <odeResource>
    <key>odeVersionId</key>
    <value>2026030310490357HZLN</value>
  </odeResource>
  <odeResource>
    <key>exe_version</key>
    <value>3.0</value>
  </odeResource>
</odeResources>
<odeProperties>
  <odeProperty>
    <key>pp_title</key>
    <value>Untitled</value>
  </odeProperty>
  <odeProperty>
    <key>pp_lang</key>
    <value>es</value>
  </odeProperty>
  <odeProperty>
    <key>pp_license</key>
    <value>creative commons: attribution - share alike 4.0</value>
  </odeProperty>
  <odeProperty>
    <key>pp_licenseUrl</key>
    <value>https://creativecommons.org/licenses/by-sa/4.0/</value>
  </odeProperty>
  <odeProperty>
    <key>pp_theme</key>
    <value>nova</value>
  </odeProperty>
  <odeProperty>
    <key>pp_exelearning_version</key>
    <value>v4.0.0-beta1</value>
  </odeProperty>
  <odeProperty>
    <key>pp_modified</key>
    <value>1772531335690</value>
  </odeProperty>
  <odeProperty>
    <key>pp_addExeLink</key>
    <value>true</value>
  </odeProperty>
  <odeProperty>
    <key>pp_addPagination</key>
    <value>false</value>
  </odeProperty>
  <odeProperty>
    <key>pp_addSearchBox</key>
    <value>false</value>
  </odeProperty>
  <odeProperty>
    <key>pp_addAccessibilityToolbar</key>
    <value>false</value>
  </odeProperty>
  <odeProperty>
    <key>pp_addMathJax</key>
    <value>false</value>
  </odeProperty>
  <odeProperty>
    <key>exportSource</key>
    <value>true</value>
  </odeProperty>
  <odeProperty>
    <key>pp_globalFont</key>
    <value>default</value>
  </odeProperty>
</odeProperties>
<odeNavStructures>
<odeNavStructure>
  <odePageId>0dd49edc-9818-434f-8727-3321461bda61</odePageId>
  <odeParentPageId></odeParentPageId>
  <pageName>New page</pageName>
  <odeNavStructureOrder>0</odeNavStructureOrder>
  <odeNavStructureProperties>
    <odeNavStructureProperty>
      <key>titlePage</key>
      <value>New page</value>
    </odeNavStructureProperty>
  </odeNavStructureProperties>
  <odePagStructures>
  </odePagStructures>
</odeNavStructure>
</odeNavStructures>
</ode>

=== jjdeharo/kit_ia_exelearning/ejemplo_content_ode.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ode SYSTEM "content.dtd">
<ode xmlns="http://www.intef.es/xsd/ode" version="2.0">
  <userPreferences>
    <userPreference>
      <key>theme</key>
      <value>base</value>
    </userPreference>
  </userPreferences>

  <odeResources>
    <odeResource>
      <key>odeId</key>
      <value>20260302100000AUTOIA</value>
    </odeResource>
    <odeResource>
      <key>odeVersionId</key>
      <value>20260302100005REV001</value>
    </odeResource>
    <odeResource>
      <key>exe_version</key>
      <value>4.x</value>
    </odeResource>
  </odeResources>

  <odeProperties>
    <odeProperty>
      <key>pp_title</key>
      <value>Ejemplo de Estructura ODE 2.0 para IA</value>
    </odeProperty>
    <odeProperty>
      <key>pp_author</key>
      <value>Assistant IA</value>
    </odeProperty>
    <odeProperty>
      <key>pp_lang</key>
      <value>es</value>
    </odeProperty>
    <odeProperty>
      <key>license</key>
      <value>creative commons: attribution - share alike 4.0</value>
    </odeProperty>
    <odeProperty>
      <key>pp_addPagination</key>
      <value>true</value>
    </odeProperty>
    <odeProperty>
      <key>pp_addSearchBox</key>
      <value>false</value>
    </odeProperty>
  </odeProperties>

  <odeNavStructures>
    <odeNavStructure>
      <odePageId>20260302PAGE001</odePageId>
      <odeParentPageId></odeParentPageId>
      <pageName>Introducción</pageName>
      <odeNavStructureOrder>1</odeNavStructureOrder>

      <odeNavStructureProperties>
        <odeNavStructureProperty>
          <key>titlePage</key>
          <value>Introducción al Curso</value>
        </odeNavStructureProperty>
        <odeNavStructureProperty>
          <key>visibility</key>
          <value>true</value>
        </odeNavStructureProperty>
      </odeNavStructureProperties>

      <odePagStructures>
        <odePagStructure>
          <odePageId>20260302PAGE001</odePageId>
          <odeBlockId>20260302BLK001</odeBlockId>
          <blockName>Bloque de Bienvenida</blockName>
          <iconName></iconName>
          <odePagStructureOrder>1</odePagStructureOrder>

          <odePagStructureProperties>
            <odePagStructureProperty>
              <key>visibility</key>
              <value>true</value>
            </odePagStructureProperty>
            <odePagStructureProperty>
              <key>teacherOnly</key>
              <value>false</value>
            </odePagStructureProperty>
            <odePagStructureProperty>
              <key>allowToggle</key>
              <value>true</value>
            </odePagStructureProperty>
            <odePagStructureProperty>
              <key>minimized</key>
              <value>false</value>
            </odePagStructureProperty>
          </odePagStructureProperties>

          <odeComponents>
            <odeComponent>
              <odePageId>20260302PAGE001</odePageId>
              <odeBlockId>20260302BLK001</odeBlockId>
              <odeIdeviceId>20260302IDEV001</odeIdeviceId>
              <odeIdeviceTypeName>text</odeIdeviceTypeName>
              <htmlView><![CDATA[<div class="exe-text-template"><div class="textIdeviceContent"><div class="exe-text-activity"><div><p>Bienvenidos a este contenido generado por una IA para eXe 4+.</p><p class="clearfix"></p></div></div></div></div>]]></htmlView>
              <jsonProperties><![CDATA[{"ideviceId":"20260302IDEV001","textInfoDurationInput":"","textInfoDurationTextInput":"Duración","textInfoParticipantsInput":"","textInfoParticipantsTextInput":"Agrupamiento","textTextarea":"<p>Bienvenidos a este contenido generado por una IA para eXe 4+.</p>","textFeedbackInput":"Show Feedback","textFeedbackTextarea":""}]]></jsonProperties>
              <odeComponentsOrder>1</odeComponentsOrder>
              <odeComponentsProperties>
                <odeComponentsProperty>
                  <key>visibility</key>
                  <value>true</value>
                </odeComponentsProperty>
                <odeComponentsProperty>
                  <key>teacherOnly</key>
                  <value>false</value>
                </odeComponentsProperty>
              </odeComponentsProperties>
            </odeComponent>
          </odeComponents>
        </odePagStructure>
      </odePagStructures>
    </odeNavStructure>
  </odeNavStructures>
</ode>

=== jjdeharo/kit_ia_exelearning/plantillas/plantilla_avanzada_aula/content.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ode SYSTEM "content.dtd">
<ode xmlns="http://www.intef.es/xsd/ode" version="2.0">
  <userPreferences>
    <userPreference>
      <key>theme</key>
      <value>base</value>
    </userPreference>
  </userPreferences>
  <odeResources>
    <odeResource>
      <key>odeId</key>
      <value>__ODE_ID__</value>
    </odeResource>
    <odeResource>
      <key>odeVersionId</key>
      <value>__ODE_VERSION_ID__</value>
    </odeResource>
    <odeResource>
      <key>exe_version</key>
      <value>4.x</value>
    </odeResource>
  </odeResources>
  <odeProperties>
    <odeProperty>
      <key>pp_title</key>
      <value>__PROJECT_TITLE__</value>
    </odeProperty>
    <odeProperty>
      <key>pp_lang</key>
      <value>es</value>
    </odeProperty>
    <odeProperty>
      <key>pp_author</key>
      <value>Plantilla IA</value>
    </odeProperty>
    <odeProperty>
      <key>license</key>
      <value>creative commons: attribution - share alike 4.0</value>
    </odeProperty>
    <odeProperty>
      <key>pp_addPagination</key>
      <value>false</value>
    </odeProperty>
    <odeProperty>
      <key>pp_addSearchBox</key>
      <value>false</value>
    </odeProperty>
  </odeProperties>
  <odeNavStructures>
    <odeNavStructure>
      <odePageId>__PAGE_ID__</odePageId>
      <odeParentPageId></odeParentPageId>
      <pageName>__PAGE_TITLE__</pageName>
      <odeNavStructureOrder>1</odeNavStructureOrder>
      <odeNavStructureProperties>
        <odeNavStructureProperty>
          <key>titlePage</key>
          <value>__PAGE_TITLE__</value>
        </odeNavStructureProperty>
        <odeNavStructureProperty>
          <key>visibility</key>
          <value>true</value>
        </odeNavStructureProperty>
      </odeNavStructureProperties>
      <odePagStructures>
        <odePagStructure>
          <odePageId>__PAGE_ID__</odePageId>
          <odeBlockId>__BLOCK_ID__</odeBlockId>
          <blockName>Texto</blockName>
          <iconName></iconName>
          <odePagStructureOrder>1</odePagStructureOrder>
          <odePagStructureProperties>
            <odePagStructureProperty>
              <key>visibility</key>
              <value>true</value>
            </odePagStructureProperty>
            <odePagStructureProperty>
              <key>teacherOnly</key>
              <value>false</value>
            </odePagStructureProperty>
            <odePagStructureProperty>
              <key>allowToggle</key>
              <value>true</value>
            </odePagStructureProperty>
            <odePagStructureProperty>
              <key>minimized</key>
              <value>false</value>
            </odePagStructureProperty>
          </odePagStructureProperties>
          <odeComponents>
            <odeComponent>
              <odePageId>__PAGE_ID__</odePageId>
              <odeBlockId>__BLOCK_ID__</odeBlockId>
              <odeIdeviceId>__IDEVICE_ID__</odeIdeviceId>
              <odeIdeviceTypeName>text</odeIdeviceTypeName>
              <htmlView><![CDATA[<div class="exe-text-template"><div class="textIdeviceContent"><div class="exe-text-activity"><div><p>Esta es una plantilla minima para generar proyectos .elpx con tema base.</p><p class="clearfix"></p></div></div></div></div>]]></htmlView>
              <jsonProperties><![CDATA[{"ideviceId":"__IDEVICE_ID__","textInfoDurationInput":"","textInfoDurationTextInput":"Duración","textInfoParticipantsInput":"","textInfoParticipantsTextInput":"Agrupamiento","textTextarea":"<p>Esta es una plantilla minima para generar proyectos .elpx con tema base.</p>","textFeedbackInput":"Show Feedback","textFeedbackTextarea":""}]]></jsonProperties>
              <odeComponentsOrder>1</odeComponentsOrder>
              <odeComponentsProperties>
                <odeComponentsProperty>
                  <key>visibility</key>
                  <value>true</value>
                </odeComponentsProperty>
                <odeComponentsProperty>
                  <key>teacherOnly</key>
                  <value>false</value>
                </odeComponentsProperty>
              </odeComponentsProperties>
            </odeComponent>
          </odeComponents>
        </odePagStructure>
      </odePagStructures>
    </odeNavStructure>
  </odeNavStructures>
</ode>
